



export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED"
export const LOAD_REVIEWS = "LOAD_REVIEWS"
export const SUBMIT_NEW_REVIEW = "SUBMIT_NEW_REVIEW"
export const BUY = "BUY"